[project]
name = "pika-pika"
version = "0.0.1"
description = "Python-based Raspberry Pi voltage logger and live web viewer"
authors = [ { name = "dwisnowski" } ]
license = "MIT"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
]

[project.optional-dependencies]
docs = ["mkdocs>=1.4", "mkdocs-material>=9.0", "mkdocs-glightbox>=0.4.0"]
